version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./SampleLinearSearch/SampleLinearSearch.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./SampleLinearSearch/SampleLinearSearch.csproj
clone_depth: 1
deploy: off